### ISSUE TITLE
Scale Preservation up to X TB

### ISSUE THREAD

**Issue by escowles** [pulibrary/figgy#1876]
Child of #1551
Blocked by #912

Scale process in #1875 up to X TB (figure out from preservation notes what the right scale is).  Get bill from Amazon to validate our estimates.

Tasks:
- [x] Select sample objects for medium-scale pilot (criteria: highest-risk items, variety of types/sizes/metadata types)
- [x] Implement optional preservation bagging triggered by setting a metadata policy, and tag selected objects to trigger generating preservation bags
- [x] Verify that bags were created as expected
- [x] Monitor cloud compute/storage bill to verify pricing estimates

**Comment by escowles** [comment]
Based on current estimates of roughly 175-200TB of data in Figgy, and price estimates in the ballpark of $2k-$5k/month (depending on the exact which storage and fixity checking options), we should target 10% of the repository (18-20TB).

**Comment by tpendragon** [comment]
Cost to fixity check 10 TB:
$568.46 - Coldline Data Retrieval
$4.74      - Cloud Function CPU Time
$2.65      - Coldline Class B Requests
$0.05      - Cloud Function Memory Time
$0.01       - Coldline Class A Requests

Total: $575.91
