### ISSUE TITLE
Migrate numismatics from Access to Figgy

### ISSUE THREAD

**Issue by escowles** [pulibrary/figgy#2025]
ToDo before migration:

- [x] Find all coin images
- [x] Find all monogram images
- [x] Ask numismatics team to change CE2 on Issue 3985 to "1918". Causing errors during import.
- [x] Fix "5709O.tif" and "5709R". Unknown tag 37680 (0x9330), is causing an error.
- [x] Make a list of duplicated images and remove dups.

**Comment by eliotjordan** [comment]
All Issues and Coins migrated to Figgy.
