### ISSUE TITLE
Implement Cloud Fixity Auditing

### ISSUE THREAD

**Issue by escowles** [pulibrary/figgy#2773]
Child of pulibrary/figgy#1876
Depends on pulibrary/figgy#2804

- [ ] Randomly retrieve preservation Bags and fixity check them
  - A javascript function will be executed with a resource ID, which will fetch the object from GCS, figure out the checksum, and put a success or failure message on a Google Cloud pub/sub queue. Figgy will run a worker to pull down those messages and create Events to store that information locally.
- [ ] Add status to Figgy object so you can tell when they were checked and what the outcome was
- [ ] Add any of this kind of failure to the Fixity dashboard.

**Comment by jrgriffiniii** [comment]
Google offers a Ruby client library for interacting with the API on https://cloud.google.com/storage/docs/reference/libraries#client-libraries-install-ruby which I shall be using in an initial approach.
