### ISSUE TITLE
Implement Embargo Support for ETDs

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/figgy#5367]
As part of the DataSpace migration project, theses and dissertations are going to be migrated to Figgy, described in MARC, and made discoverable in the catalog. Some theses and dissertations have embargoes associated with them. To support this use case, Figgy admins need to be able to enforce a content embargo for an object, making files associated with it inaccessible before the embargo date specified.

### Students

Students submit their ETDs into a SharePoint site, which is managed by OIT. They submit if they need some form of embargo.

### RDSS

1. Once a year RDSS receives a spreadsheet that contains title, depositor, access restrictions after embargo, embargo requirements for every ETD, and a `walk_in` field, which determines if (after the embargo is lifted) people can walk into Mudd to see the content digitally
    - We're not sure what "walk in" actually means and the workflow they need to support. We think this is equivalent to "reading room" visibility, but @kelynch is getting clarity.
1. RDSS also gets all the PDFs for every ETD. They're always a PDF.
2. RDSS packages up the ETDs with the visibility and embargo information. RIght now it's packaged up for DSpace, but they could package it up in a format for Figgy instead.
3. RDSS ingests it into the repository - for Figgy we think this would be a bulk ingest.

### DLS (Figgy)

1. On bulk ingest Figgy needs to be able to assign an embargo_date (Something like 2022-09-01) and a visibility on a per-item basis, despite ingesting hundreds of PDFs.
2. If an embargo is set and it hasn't passed, that record should be treated as "Private" NO MATTER WHAT. It should be very clear that an embargo is set.
3. 2022-09-01 means at Midnight Eastern Time on September 1st the record is available with whatever visibility was originally assigned. We should probably store a UTC time or something translated from a date picker in the UI. Or just ISO8601 with a timezone component.

### Visibility

DSpace offers four levels of visibility after embargo:

Closed
  * Bitstreams can't be downloaded, aren't discoverable, and technical metadata isn't visible. Resource metadata is discoverable, you just don't know there's a file.
  * This should be the same as "Private" in Figgy

Open - On Campus / VPN Access
  * Users with a campus IP address should be able to access the content. This is the same as Figgy's "on campus" option

Open - On Campus, IP-Restricted
  * We think this is if `walk_in` is set. We're seeking clarity from special collections. We think the idea is if you're at a special computer you can see this. We think this is the equivalent of "readingroom" in Figgy, but there's a workflow for requesting access to material that wouldn't exist in the Catalog. This is the biggest question for visibility.

Open - World Readable
  * This is Figgy's "Open"

## History

We originally thought we'd store the embargo in the MARC metadata, but worried that we'd run afoul of descriptive practices on existing records (506s in non-theses and dissertations) and, as sync has at minimum a several hour delay from Alma -> Orangelight, we needed to ensure that embargoes could be extended in a hurry.

## Current Documentation

https://undergraduateresearch.princeton.edu/independent-work/thesis-archive

## Tasks

- [x] Add a way for bulk ingest to assign visibility/embargo date on a per-object basis.
    * Initial thoughts around this have been a file in the folder for an object that's like `figgy_metadata.json` or `figgy_metadata.yml`, needs some consensus.
- [x] Add embargo_date property.
- [x] Enforce embargo_date property.

**Comment by kelynch** [comment]
"Walk-in" access is confirmed as being the following currently: if, **after the embargo date has elapsed** a thesis/dissertation has walk-in access set to "yes," this means that users can only access the file at a dedicated desktop machine with a fixed IP, in the Mudd Reading Room.

**Comment by kelynch** [comment]
Additional resource on embargo types - https://undergraduateresearch.princeton.edu/independent-work/thesis-archive

**Comment by tpendragon** [comment]
> "Walk-in" access is confirmed as being the following currently: if, **after the embargo date has elapsed** a thesis/dissertation has walk-in access set to "yes," this means that users can only access the file at a dedicated desktop machine with a fixed IP, in the Mudd Reading Room.

This reads like our `readingroom` use case with IPs being set for those machines (would be great, we've had that feature for years and haven't been able to implement it) - it would mean those machines would also be able to access other reading room only material. If we're okay with that, then great. We just need the IPs.

@kelynch is gonna follow up and get back to us.

**Comment by kelea99** [comment]
Thanks, @kelynch ! ok. Reading through the embargo types and expectations on that page,  I see a few things in the document you shared that seem contradictory to above (and I just want to make sure I understand correctly). 

- [](To enhance the reach and utility of this resource, the [library created a digital archive in 2014 ](http://undergraduateresearch.princeton.edu/feature-article/senior-thesis-archive-goes-digital)to enable members of the Princeton University community (our students, faculty, staff) and other authorized users of our computing network to access copies of senior theses online.) : This does not sound like Open. This sounds like Princeton University Net ID or getting access to view something via SC?  
- Online Access: _accessible online to authorized users of the Princeton University computing network (as described above)._ again, this sounds like Princeton Net ID/access via SC.
- Walk-in Access Only: as you note above. If they want their desktop to hang with Figgy, we had to have Steph A. and her team come in to help with that as well for Special Collections. Has Steph been over there to see what the setup is like? 
Am I reading this correctly?

**Comment by kelynch** [comment]
Here are the Mudd workstation IPs that can access walk-in theses - https://github.com/PrincetonUniversityLibrary/princeton-5/blob/dataspace-prod/dspace/config/modules/authentication-ip.cfg#L313

**Comment by kelynch** [comment]
> Thanks, @kelynch ! ok. Reading through the embargo types and expectations on that page, I see a few things in the document you shared that seem contradictory to above (and I just want to make sure I understand correctly).

Thanks @kelea99!  To try to answer your questions in order:

> To enhance the reach and utility of this resource, the [library created a digital archive in 2014 (http://undergraduateresearch.princeton.edu/feature-article/senior-thesis-archive-goes-digital)to enable members of the Princeton University community (our students, faculty, staff) and other authorized users of our computing network to access copies of senior theses online.) : This does not sound like Open. This sounds like Princeton University Net ID or getting access to view something via SC?

Sorry, I'm not sure what "SC" refers to here?  It sounds like on-campus or VPN access.  While most items in DataSpace are only accessible over the VPN or on-campus, there are some that are completely open.  Users do not log into DataSpace to access materials.

> Online Access: accessible online to authorized users of the Princeton University computing network (as described above). again, this sounds like Princeton Net ID/access via SC.

I think this is VPN or on-campus access as well.

> Walk-in Access Only: as you note above. If they want their desktop to hang with Figgy, we had to have Steph A. and her team come in to help with that as well for Special Collections. Has Steph been over there to see what the setup is like?

I'm meeting with Christa today and should be able to get back to you with more info on this!


* The summary in the abo

**Comment by kelea99** [comment]
Thank you, @kelynch ! SC is "Special Collections" in this context and I have edited my original comment accordingly, spelling out the acronym. sorry about that!! :)

**Comment by tpendragon** [comment]
Some more information about the click-through:

In DSpace, all Theses have a click-through to access the content. It looks like this:

![image001](https://user-images.githubusercontent.com/2806645/187990651-80ce859b-2bca-4cdd-ab5d-a617b7299110.jpg)

This click-through was generated in collaboration with the Office of the Dean of the College, which creates access policies for undergraduate theses.

I'm trying to get Lynn, Christa, myself, and Kate together at some point to talk through this, but I suspect we're going to have to implement this click-through somehow.

**Comment by tpendragon** [comment]
See https://dataspace.princeton.edu/handle/88435/dsp01jm214s331 while on VPN

**Comment by tpendragon** [comment]
We have a meeting scheduled for September 12. So - we're blocked here.

**Comment by tpendragon** [comment]
Embargos are implemented. The other tickets mentioned here can be found in #5439 and #5438.
