### ISSUE TITLE
File picker: in directory mode, select directories in right pane

### ISSUE THREAD

**Issue by hackartisan** [pulibrary/figgy#5836]
### Summary

The target selected for ingest should always be selected from the right pane, for UX consistency between file mode and directory mode. Currently in directory mode the directory can be selected on the smaller left pane, and then "ingest this directory" can be clicked from the right pane. It would be more intuitive to select the directory to ingest in the right pane.

### Impact
We want to improve our responsiveness to user feedback about newly deployed features.

### Implementation Steps

- [ ] Generate a wireframe for what it would look like to select directories to ingest from the right pane
- [ ] Share those wireframes with the Studio & Christa.
      * Do this via a meeting.
- [ ] If that's agreed to, look into execution.

### Priority recommendation

- [ ] asap
- [ ] within the next 3 weeks
- [x] PO will prioritize

## Sudden Priority Justification
_Required if "asap" or "within the next 3 weeks" is checked. Add "Sudden Priority" and "Maintenance/Research" labels_

### Steps to reproduce behaviour
Compare the UX of the file picker in a bulk ingest context with the file picker in a file manager "ingest from server" context.

### Screenshots
![Screenshot 2023-05-19 at 11 30 37 AM](https://github.com/pulibrary/figgy/assets/845363/b6dab1c9-3fe4-490a-8cb8-632e8bf73ee0)
![Screenshot 2023-05-19 at 11 31 52 AM](https://github.com/pulibrary/figgy/assets/845363/86971b68-7e09-4450-a7c9-0e96e2aefaff)

**Comment by kelea99** [comment]
Agreed. if this was requested by users, would this be a good MULE ticket, @hackartisan ? Regardless, it should be prioritized versus put on a back burner, if you want my thoughts

**Comment by hackartisan** [comment]
Yes, based on discussion during our retro, we thought this would be good as our next mule ticket!

**Comment by tpendragon** [comment]
We think training has solved this problem enough at least.
