### ISSUE TITLE
EPIC: MMS ID and Holdings ID - how to implement? 

### ISSUE THREAD

**Issue by kelea99** [pulibrary/figgy#5881]
### Summary

- [ ] https://github.com/pulibrary/figgy/issues/5880
- [ ] 

### Impact 
_Please include hard deadlines, if the exhibit is part of an event, the issue is stopping work, etc._

### Priority recommendation

- [ ] asap
- [ ] within the next 3 weeks
- [ ] PO will prioritize

## Sudden Priority Justification
_Required if "asap" or "within the next 3 weeks" is checked. Add "Sudden Priority" and "Maintenance/Research" labels_
