### ISSUE TITLE
Ingest Ethiopic MSS

### ISSUE THREAD

**Issue by escowles** [pulibrary/figgy#810]
- [x] DPUL display https://github.com/pulibrary/pomegranate/issues/309
- [ ] PULFA metadata extraction https://github.com/pulibrary/pul_metadata_services/issues/22
- [x] PULFA viewer https://github.com/pulibrary/pulfa/issues/267
- [ ] OL indexing https://github.com/pulibrary/orangelight/issues/1188

**Comment by tpendragon** [comment]
Closed. There's a DPUL exhibit.
